environments:
  dev:
    values:
      - version: 0.3.0
---
repositories:
- name: dev-backends
  url: https://suitenumerique.github.io/helm-dev-backend
---

releases:
  - name: dev-backend
    namespace: {{ .Namespace }}
    chart: dev-backends/dev-backend
    version: 0.0.2
    values:
      - postgres:
          enabled: true
          name: postgres
          #serviceNameOverride: postgres
          image: postgres:16-alpine
          username: dinum
          password: pass
          database: dinum
          size: 1Gi
      - redis:
          enabled: true
          name: redis
          #serviceNameOverride: redis
          image: redis:8.2-alpine
          username: user
          password: pass
      - minio:
          enabled: true
          image: minio/minio
          name: minio
          # serviceNameOverride: drive-minio
          ingress:
            enabled: true
            hostname: drive-minio.127.0.0.1.nip.io
            tls:
              enabled: true
              secretName: drive-tls
          consoleIngress:
            enabled: true
            hostname: drive-minio-console.127.0.0.1.nip.io
            tls:
              enabled: true
              secretName: drive-tls
          username: dinum
          password: password
          bucket: drive-media-storage
          versioning: true
          size: 1Gi
      - keycloak:
          enabled: true
          image: quay.io/keycloak/keycloak:20.0.1
          name: keycloak
          #serviceNameOverride: keycloak
          hostname: drive-keycloak.127.0.0.1.nip.io
          username: admin
          password: pass
          tls:
            enabled: true
            secretName: drive-tls
          db:
            username: dinum
            password: pass
            database: keycloak
            size: 1Gi
            image: postgres:16-alpine
          realm:
            name: drive
            username: drive
            password: drive
            email: drive@example.com

  - name: drive
    version: {{ .Values.version }}
    namespace: {{ .Namespace }}
    chart: ./drive
    values:
      - env.d/{{ .Environment.Name }}/values.drive.yaml.gotmpl